### ISSUE TITLE
set img tag be background

### ISSUE THREAD

**Issue by twice7713** [AdaRoseCannon/aframe-htmlmesh#18]
I read https://aframe.wiki/en/#!pages/gui.md page.
it say support images with img tags
```
 const imgStyle = {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  }

  return (
    <React.Fragment>
      <div id='chat-interface' class={isPC ? 'speech-bubble-PC' : 'speech-bubble-Phone'}>
        <img src={plane} alt='Description of the image' style={imgStyle} />
        <div id='character1'>{character}</div>
        <div id='message1'>{isTyping1 ? textToDisplay1 : message1}</div>
      </div>
    </React.Fragment>
  )
```
but ,but img tag not work,i want to set img be background

**Comment by vincentfretin** [comment]
There is one thing that is not implemented in HTMLMesh, it's waiting for image to be loaded before doing the render. So in your case maybe the render is done, the image is loaded and no rerender of the HTMLMesh canvas is done after that.
I don't have the issue in my projects because I set the `html` component in javascript in a `enter-vr` listener, so I'm pretty sure the image is loaded before I click the VR button.
You could also try to create a `useEffect` that check `imgEl.complete` or otherwise add `imgEl.addEventListener("loaded", ...)` that would call `interfaceEl.components.html.rerender()` when you know the image is loaded.

**Comment by twice7713** [comment]
First of all thank you for your response
But sorry, I'm a beginner and I don't know how to implement the approach you provided
can you give me some example

**Comment by twice7713** [comment]
![Myscript](https://github.com/AdaRoseCannon/aframe-htmlmesh/assets/57941062/498fcc2d-163d-4888-a4bb-d5d973959ab6)

**Comment by vincentfretin** [comment]
In your img onLoad function, try:
```
document.getElementById('a-chat')?.components.html.rerender()
```

**Comment by vincentfretin** [comment]
Oh image support was only on master and the build wasn't up to date. Be sure to use latest 2.1.0 that have image support.

**Comment by vincentfretin** [comment]
I close. You can reopen if you still have an issue.
